//YOUR FIREBASE LINKS
const firebaseConfig = {
      apiKey: "AIzaSyCBPNzG6vXq2-Ydi6rPiRAWUUaqikt5dN0",
      authDomain: "chaty-bird.firebaseapp.com",
      databaseURL: "https://chaty-bird-default-rtdb.firebaseio.com",
      projectId: "chaty-bird",
      storageBucket: "chaty-bird.appspot.com",
      messagingSenderId: "368324438363",
      appId: "1:368324438363:web:88af72eafb719357f2527e"
};
firebase.initializeApp(firebaseConfig);

user_name = localStorage.getItem("username");
room_name = localStorage.getItem("room_name");

function send() {
      msg = document.getElementById("msg").value;
      console.log(msg);
      firebase.database().ref(room_name).push({
            name: user_name,
            likes: 0,
            message: msg
      })
      document.getElementById("msg").innerHTML = "";
}


function logout() {
      localStorage.removeItem("username");
      localStorage.removeItem("room_name");
      window.location = "index.html";
}


function getData() {
      firebase.database().ref("/" + room_name).on('value', function (snapshot) {
            document.getElementById("output").innerHTML = ""; snapshot.forEach(function (childSnapshot) {
                  childKey = childSnapshot.key; childData = childSnapshot.val(); if (childKey != "purpose") {
                        firebase_message_id = childKey;
                        message_data = childData;
                        //The firebase_message_id variable holds all the unique message id generated by the firebase.
                        //The message_data variable holds all the messages, likes and username for every message.

                        //Start code
                        console.log(firebase_message_id + ": ")
                        console.log(message_data);
                        name = message_data['name'];
                        like = message_data['likes'];
                        message = message_data['message'];
                        name_tag = "<h4 >" + name + "<img src='tick.png' class='user_tick'></h4>";
                        message_tag = "<h4 class='message h4'>" + message + "</h4>";
                        button_tag = "<button class='btn btn-warning' id=" + firebase_message_id + " value=" + like + " onclick='updateLike(this.id)'>";
                        img_with_button = "<span class='glyphicon glyphicon-thumbs-up-like'>Like: " + like + "</span></button><hr>"
                        row = name_tag + message_tag + button_tag + img_with_button;
                        document.getElementById("output").innerHTML += row;


                        //End code
                  }
            });
      });
}
getData();

function updateLike(message_id) {
      console.log("Likes:" + like);
      button_id = message_id;
      likes = document.getElementById(button_id).value;
      updatelikes = Number(likes) + 1;

      firebase.database().ref(room_name).child(message_id).update({
            likes:updatelikes
      });
}

